# Loads default set of integrations. Do not remove.
default_config:

# Core config
homeassistant:
  # Load customizations
  customize: !include customize/entity.yaml
  customize_domain: !include customize/domain.yaml
  customize_glob: !include customize/glob.yaml
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Recorder config
recorder: !include recorder.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 10.0.0.0/8
    - 192.168.0.0/16
    - 209.137.204.0/22
    - 209.137.203.0/24
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22
    - 2400:cb00::/32
    - 2606:4700::/32
    - 2803:f800::/32
    - 2405:b500::/32
    - 2405:8100::/32
    - 2a06:98c0::/29
    - 2c0f:f248::/32

##
# INTEGRATIONS
#

# Battery Notes
battery_notes:
  enable_autodiscovery: true
  show_all_devices: true
  enable_replaced: true
  default_battery_low_threshold: 15
  battery_increase_threshold: 25
  hide_battery: true
  round_battery: true

# PowerCalc
powercalc:

# InfluxDB 2
influxdb:
  api_version: 2
  ssl: true
  host: influxdb.lloydnet.org
  port: 8086
  token: !secret influxdb_token
  organization: Slacknet
  bucket: home_assistant

##
# ADDITIONAL INCLUDES
#

# HomeKit
homekit: !include homekit.yaml
# Automations
automation: !include automations.yaml
# Scripts
script: !include scripts.yaml
# Shell commands
shell_command: !include shell_commands.yaml
# Notify
notify: !include notify.yaml
# iOS/Mac Actions
ios: !include ios_actions.yaml
