##
# Core config
#
# Loads default set of integrations. Do not remove.
default_config:
homeassistant:
  # Load customizations
  customize: !include customize/entity.yaml
  customize_domain: !include customize/domain.yaml
  customize_glob: !include customize/glob.yaml
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes


##
# INTEGRATIONS
#

# Battery Notes
battery_notes:
  enable_autodiscovery: true
  show_all_devices: true
  enable_replaced: true
  default_battery_low_threshold: 15
  battery_increase_threshold: 25
  hide_battery: true
  round_battery: true

# PowerCalc
powercalc:

# InfluxDB 2
influxdb:
  api_version: 2
  ssl: true
  host: influxdb.lloydnet.org
  port: 8086
  token: !secret influxdb_token
  organization: Slacknet
  bucket: home_assistant

##
# ADDITIONAL INCLUDES
#

# Recorder config
recorder: !include recorder.yaml
# HTTP configuration
http: !include http.yaml
# HomeKit
homekit: !include homekit.yaml
# Automations
automation: !include automations.yaml
# Scripts
script: !include scripts.yaml
# Shell commands
shell_command: !include shell_commands.yaml
# Notify
notify: !include notify.yaml
# iOS/Mac Actions
ios: !include ios_actions.yaml
